### ISSUE TITLE
having the app open increases menu bar spacing

### ISSUE THREAD

**Issue by Tallak-Lippe** [Jaysce/Jukebox#4]
This happened on my new MacBook Pro 14 inch with notch, on the latest version of the app and the latest version of Monterey. It fixes itself when I quit Jukebox

**Comment by Jaysce** [comment]
Not sure what you mean by this, could you post a screenshot?

**Comment by Xyth** [comment]
That's a "feature" of Monterey, nothing to do with Jukebox. If you have a lot of items in the menubar it tries to space them out between the notch and the corner.

**Comment by Jaysce** [comment]
Closing this as it is not an issue with Jukebox.
